"""add_columns

Revision ID: 1706a1bee70c
Revises: 
Create Date: 2026-07-12 15:45:24.013462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1706a1bee70c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rejected_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['approved_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by_user_id')
        batch_op.drop_column('approved_by_user_id')

    # ### end Alembic commands ###
