"""add_maintenance_columns

Revision ID: bdddabbb15b8
Revises: 1706a1bee70c
Create Date: 2026-07-12 16:09:10.275050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdddabbb15b8'
down_revision = '1706a1bee70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_technician_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('maintenance_requests_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['approved_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['rejected_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'technicians', ['assigned_technician_id'], ['id'])
        batch_op.drop_column('technician_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('maintenance_requests_ibfk_3'), 'technicians', ['technician_id'], ['id'])
        batch_op.drop_column('started_at')
        batch_op.drop_column('rejected_by_user_id')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('approved_by_user_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('assigned_technician_id')

    # ### end Alembic commands ###
