{
    'name': 'AssetFlow Management',
    'version': '1.0.0',
    'summary': 'Enterprise asset and resource management',
    'description': 'Odoo addon for managing assets, departments, maintenance, bookings, and audits.',
    'author': 'AssetFlow Team',
    'depends': ['base'],
    'data': [
        'security/assetflow_security.xml',
        'security/ir.model.access.csv',
        'views/asset_views.xml',
        'views/asset_request_views.xml',
        'views/report_views.xml',
        'reports/asset_inventory_report.xml',
        'views/allocation_views.xml',
        'views/department_views.xml',
        'views/employee_views.xml',
        'views/maintenance_views.xml',
        'views/booking_views.xml',
        'views/audit_views.xml',
        'views/menu_views.xml',
        'data/asset_data.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
